### ISSUE TITLE
Set up secrets to that database actions can be run on commit

### ISSUE THREAD

**Issue by simsong** [simsong/digitalcorpora-stats#23]
See:
https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by joedinsmoor** [comment]
I don't have access to the repo settings for this repo. I created a separate credentials file with dummy credentials in the meantime. (credlib.py)

**Comment by simsong** [comment]
Right. I'm the person who has to do this.
What's credlib?

**Comment by simsong** [comment]
(Notice that it's assigned to me!)

**Comment by joedinsmoor** [comment]
credlib is a small doc containing dummy credentials so that I can continue to iterate upon webdb_test.py while the secrets are being setup

**Comment by joedinsmoor** [comment]
Purely a temporary usage

**Comment by simsong** [comment]
Oh, I suggest that you just put the credentials in an environment variable with your .bashrc file and then read them with getenv, as I did in the test program.

**Comment by simsong** [comment]
Closed by https://github.com/simsong/digitalcorpora-stats/issues
