### ISSUE TITLE
Design Database Schema

### ISSUE THREAD

**Issue by joedinsmoor** [simsong/digitalcorpora-stats#7]
![image](https://user-images.githubusercontent.com/55299247/81717334-67e77680-9448-11ea-91d4-51663e8d8675.png)
Database Schema so far ^

_Originally posted by @joedinsmoor in https://github.com/simsong/joe_summer_2020/issues/6#issuecomment-627437181_

**Comment by simsong** [comment]
Want me to put together the first draft on the DB schema?

**Comment by joedinsmoor** [comment]
Sure.

**Comment by simsong** [comment]
We now have a database schema: https://github.com/simsong/digitalcorpora-stats/pull/18
Here is the schema: https://github.com/simsong/digitalcorpora-stats/blob/master/python/schema.sql

For an idea of how to do inserts, look at this:
* https://github.com/simsong/digitalcorpora-stats/blob/master/python/schema.sql

**Comment by simsong** [comment]
The database schema is now designed and you can add a test to schema_test.py to test it!

**Comment by simsong** [comment]
Closed by https://github.com/simsong/digitalcorpora-stats/pull/30
